### ISSUE TITLE
Can't convert 'list' object to str implicitly

### ISSUE THREAD

**Issue by bradsherman** [zchee/deoplete-clang#49] opened 2016-08-10 01:38 UTC
## Problems summary

I am trying to use this on a simple helloworld.c, but when the autocompletion is triggered, an error occurs and asks me to execute :messages. The error arises from the deoplete_clang.py file in the gather_candidates function, specifically in the line containing "self.get_minimum_flags(context['filetype']). Then it says TypeError: can't convert 'list' object to object str implicitly.

## Expected

Automatically provide C/C++ completion without error messages.

## Environment Information

 - OS: Ubuntu 16.04
 - Neovim version: NVIM 0.1.5-dev

## Provide a minimal init.vim with less than 50 lines and not plugin manager (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim/
set runtimepath+=~/.config/nvim/plugged/deoplete-clang/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. nvim -u minimal-init.vim {any simple c/c++ program}
 2. Enter insert mode, type the beginning of a word and wait for autocomplete to trigger
 3. In normal mode, enter :messages to see the error.

**Comment by DarkDefender** [comment] 2016-08-10 14:42
It seems to be a problem with the default value of `completion_flags`. It inits to a empty string if you haven't defined it yourself (it should be empty list). So you need to change the following line to get it to work.

```
--- a/rplugin/python3/deoplete/sources/deoplete_clang.py
+++ b/rplugin/python3/deoplete/sources/deoplete_clang.py
@@ -44,7 +44,7 @@ class Source(Base):
         )
         self.completion_flags = vars.get(
             'deoplete#sources#clang#flags',
-            ''
+            []
         )
         self.sort_algo = vars.get(
             'deoplete#sources#clang#sort_algo',
```

**Comment by bradsherman** [comment] 2016-08-10 15:06
that fixed it, thanks!

**Comment by DarkDefender** [comment] 2016-08-10 15:33
I think you shouldn't close this issue until this is fixed. The default values shouldn't prevent this plugin from working after all...

**Comment by bradsherman** [comment] 2016-08-10 16:53
Sorry, I am new to this process. Should I make a pull request?

**Comment by DarkDefender** [comment] 2016-08-10 19:07
@bradsherman I guess you could create a pull request if you want to. I'm not 100% sure that this is the correct way to fix this though so perhaps we should wait for input from @zchee

**Comment by nhooyr** [comment] 2016-08-11 01:08
This is a regression from #41 and #47. I've opened #50 to address this.

**Closed** 2016-08-11 03:59 UTC
